### ISSUE TITLE
Doesn't build with current Rack master branch

### ISSUE THREAD

**Issue by bontric** [VCVRack/Fundamental#21]
Trying to compile Fundamental with current Rack  master branch doesn't work. I'm getting the following errors:

```make
src/SequentialSwitch.cpp:15:8: error: expected '= constant-expression' or end of
      enumerator definition
                ENUMS(IN_INPUT, TYPE == 1 ? 1 : 4),
                     ^
src/SequentialSwitch.cpp:19:3: error: redefinition of enumerator 'ENUMS'
                ENUMS(OUT_OUTPUT, TYPE == 1 ? 4 : 1),
                ^
src/SequentialSwitch.cpp:15:3: note: previous definition is here
                ENUMS(IN_INPUT, TYPE == 1 ? 1 : 4),
                ^
src/SequentialSwitch.cpp:19:8: error: expected '= constant-expression' or end of
      enumerator definition
                ENUMS(OUT_OUTPUT, TYPE == 1 ? 4 : 1),
                     ^
src/SequentialSwitch.cpp:23:3: error: redefinition of enumerator 'ENUMS'
                ENUMS(CHANNEL_LIGHT, 4),
                ^
src/SequentialSwitch.cpp:15:3: note: previous definition is here
                ENUMS(IN_INPUT, TYPE == 1 ? 1 : 4),
                ^
src/SequentialSwitch.cpp:23:8: error: expected '= constant-expression' or end of
      enumerator definition
                ENUMS(CHANNEL_LIGHT, 4),
                     ^
src/SequentialSwitch.cpp:59:23: error: use of undeclared identifier 'IN_INPUT'
                        float out = inputs[IN_INPUT + 0].value;
                                           ^
src/SequentialSwitch.cpp:61:13: error: use of undeclared identifier 'OUT_OUTPUT'; did
      you mean 'NUM_OUTPUTS'?
                                outputs[OUT_OUTPUT + i].value = channelFilter[i]...
                                        ^~~~~~~~~~
                                        NUM_OUTPUTS
src/SequentialSwitch.cpp:20:3: note: 'NUM_OUTPUTS' declared here
                NUM_OUTPUTS
                ^
src/SequentialSwitch.cpp:67:42: error: use of undeclared identifier 'IN_INPUT'
                                out += channelFilter[i].out * inputs[IN_INPUT + ...
                                                                     ^
src/SequentialSwitch.cpp:69:12: error: use of undeclared identifier 'OUT_OUTPUT'; did
      you mean 'NUM_OUTPUTS'?
                        outputs[OUT_OUTPUT + 0].value = out;
                                ^~~~~~~~~~
                                NUM_OUTPUTS
src/SequentialSwitch.cpp:20:3: note: 'NUM_OUTPUTS' declared here
                NUM_OUTPUTS
                ^
src/SequentialSwitch.cpp:74:11: error: use of undeclared identifier 'CHANNEL_LIGHT'
                        lights[CHANNEL_LIGHT + i].setBrightness(channelFilter[i].out);
                               ^
src/SequentialSwitch.cpp:89:23: error: use of undeclared identifier 'CKSSThree'
        addParam(createParam<CKSSThree>(mm2px(Vec(5.24619, 46.9153)), module, TS...
                             ^
src/SequentialSwitch.cpp:93:92: error: no member named 'IN_INPUT' in
      'SequentialSwitch<1>'
  ...62.8096)), module, TSequentialSwitch::IN_INPUT + 0));
                        ~~~~~~~~~~~~~~~~~~~^
src/SequentialSwitch.cpp:95:94: error: no member named 'OUT_OUTPUT' in
      'SequentialSwitch<1>'; did you mean 'NUM_OUTPUTS'?
  ...77.8095)), module, TSequentialSwitch::OUT_OUTPUT + 0));
                        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
                                           NUM_OUTPUTS
src/SequentialSwitch.cpp:20:3: note: 'NUM_OUTPUTS' declared here
                NUM_OUTPUTS
                ^
src/SequentialSwitch.cpp:96:94: error: no member named 'OUT_OUTPUT' in
      'SequentialSwitch<1>'; did you mean 'NUM_OUTPUTS'?
  ...87.8113)), module, TSequentialSwitch::OUT_OUTPUT + 1));
                        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
                                           NUM_OUTPUTS
src/SequentialSwitch.cpp:20:3: note: 'NUM_OUTPUTS' declared here
                NUM_OUTPUTS
                ^
src/SequentialSwitch.cpp:97:93: error: no member named 'OUT_OUTPUT' in
      'SequentialSwitch<1>'; did you mean 'NUM_OUTPUTS'?
  ...97.809)), module, TSequentialSwitch::OUT_OUTPUT + 2));
                       ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
                                          NUM_OUTPUTS
src/SequentialSwitch.cpp:20:3: note: 'NUM_OUTPUTS' declared here
                NUM_OUTPUTS
                ^
src/SequentialSwitch.cpp:98:94: error: no member named 'OUT_OUTPUT' in
      'SequentialSwitch<1>'; did you mean 'NUM_OUTPUTS'?
  ...107.809)), module, TSequentialSwitch::OUT_OUTPUT + 3));
                        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
                                           NUM_OUTPUTS
src/SequentialSwitch.cpp:20:3: note: 'NUM_OUTPUTS' declared here
                NUM_OUTPUTS
                ^
src/SequentialSwitch.cpp:100:103: error: no member named 'CHANNEL_LIGHT' in
      'SequentialSwitch<1>'
  ...77.7158)), module, TSequentialSwitch::CHANNEL_LIGHT + 0));
                        ~~~~~~~~~~~~~~~~~~~^
src/SequentialSwitch.cpp:101:103: error: no member named 'CHANNEL_LIGHT' in
      'SequentialSwitch<1>'
  ...87.7163)), module, TSequentialSwitch::CHANNEL_LIGHT + 1));
                        ~~~~~~~~~~~~~~~~~~~^
src/SequentialSwitch.cpp:102:103: error: no member named 'CHANNEL_LIGHT' in
      'SequentialSwitch<1>'
  ...97.7167)), module, TSequentialSwitch::CHANNEL_LIGHT + 2));
                        ~~~~~~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

```

(Note: Everything compiles fine with the v0.5 branch)

**Comment by KieranPringle** [comment]
See: https://github.com/VCVRack/Fundamental/issues/19#issuecomment-353607338

**Comment by bontric** [comment]
Ugh.. should've checked the issues.. Sorry and  thanks @KieranPringle

**Comment by AndrewBelt** [comment]
It should actually work now. Building for v0.5 requires checking out the `v0.5.0` tag with `git checkout v0.5.0`
